export const flightSeat = [
    {
        type: 'A',
        seat: [
            { code: 'A1', available: true },
            { code: 'A2', available: false },
            { code: 'A3', available: true },
            { code: 'A4', available: true },
            { code: 'A5', available: true },
            { code: 'A6', available: false },
            { code: 'A7', available: false },
            { code: 'A8', available: true },
            { code: 'A9', available: true },
            { code: 'A10', available: true },
            { code: 'A11', available: false },
            { code: 'A12', available: true },
        ],
    },
    {
        type: 'B',
        seat: [
            { code: 'B1', available: true },
            { code: 'B2', available: false },
            { code: 'B3', available: true },
            { code: 'B4', available: true },
            { code: 'B5', available: true },
            { code: 'B6', available: false },
            { code: 'B7', available: false },
            { code: 'B8', available: true },
            { code: 'B9', available: true },
            { code: 'B10', available: true },
            { code: 'B11', available: false },
            { code: 'B12', available: true },
        ],
    },
    {
        type: 'C',
        seat: [
            { code: 'C1', available: true },
            { code: 'C2', available: false },
            { code: 'C3', available: true },
            { code: 'C4', available: false },
            { code: 'C5', available: true },
            { code: 'C6', available: false },
            { code: 'C7', available: false },
            { code: 'C8', available: true },
            { code: 'C9', available: true },
            { code: 'C10', available: true },
            { code: 'C11', available: false },
            { code: 'C12', available: true },
        ],
    },
    {
        type: 'D',
        seat: [
            { code: 'D1', available: true },
            { code: 'D2', available: true },
            { code: 'D3', available: true },
            { code: 'D4', available: false },
            { code: 'D5', available: false },
            { code: 'D6', available: false },
            { code: 'D7', available: false },
            { code: 'D8', available: false },
            { code: 'D9', available: false },
            { code: 'D10', available: true },
            { code: 'D11', available: true },
            { code: 'D12', available: false },
        ],
    },
    {
        type: 'E',
        seat: [
            { code: 'E1', available: true },
            { code: 'E2', available: true },
            { code: 'E3', available: true },
            { code: 'E4', available: false },
            { code: 'E5', available: false },
            { code: 'E6', available: false },
            { code: 'E7', available: false },
            { code: 'E8', available: false },
            { code: 'E9', available: false },
            { code: 'E10', available: true },
            { code: 'E11', available: true },
            { code: 'E12', available: false },
        ],
    },
    {
        type: 'F',
        seat: [
            { code: 'F1', available: true },
            { code: 'F2', available: true },
            { code: 'F3', available: false },
            { code: 'F4', available: false },
            { code: 'F5', available: false },
            { code: 'F6', available: true },
            { code: 'F7', available: false },
            { code: 'F8', available: false },
            { code: 'F9', available: false },
            { code: 'F10', available: true },
            { code: 'F11', available: true },
            { code: 'F12', available: false },
        ],
    },
];

export const flightSeatDepart = [
    {
        type: 'A',
        seat: [
            { code: 'A1', available: true },
            { code: 'A2', available: false },
            { code: 'A3', available: true },
            { code: 'A4', available: true },
            { code: 'A5', available: true },
            { code: 'A6', available: false },
            { code: 'A7', available: false },
            { code: 'A8', available: true },
            { code: 'A9', available: true },
            { code: 'A10', available: true },
            { code: 'A11', available: false },
            { code: 'A12', available: true },
        ],
    },
    {
        type: 'B',
        seat: [
            { code: 'B1', available: true },
            { code: 'B2', available: false },
            { code: 'B3', available: true },
            { code: 'B4', available: true },
            { code: 'B5', available: true },
            { code: 'B6', available: false },
            { code: 'B7', available: false },
            { code: 'B8', available: true },
            { code: 'B9', available: true },
            { code: 'B10', available: true },
            { code: 'B11', available: false },
            { code: 'B12', available: true },
        ],
    },
    {
        type: 'C',
        seat: [
            { code: 'C1', available: true },
            { code: 'C2', available: false },
            { code: 'C3', available: true },
            { code: 'C4', available: false },
            { code: 'C5', available: true },
            { code: 'C6', available: false },
            { code: 'C7', available: false },
            { code: 'C8', available: true },
            { code: 'C9', available: true },
            { code: 'C10', available: true },
            { code: 'C11', available: false },
            { code: 'C12', available: true },
        ],
    },
    {
        type: 'D',
        seat: [
            { code: 'D1', available: true },
            { code: 'D2', available: true },
            { code: 'D3', available: true },
            { code: 'D4', available: false },
            { code: 'D5', available: false },
            { code: 'D6', available: false },
            { code: 'D7', available: false },
            { code: 'D8', available: false },
            { code: 'D9', available: false },
            { code: 'D10', available: true },
            { code: 'D11', available: true },
            { code: 'D12', available: false },
        ],
    },
    {
        type: 'E',
        seat: [
            { code: 'E1', available: true },
            { code: 'E2', available: true },
            { code: 'E3', available: true },
            { code: 'E4', available: false },
            { code: 'E5', available: false },
            { code: 'E6', available: false },
            { code: 'E7', available: false },
            { code: 'E8', available: false },
            { code: 'E9', available: false },
            { code: 'E10', available: true },
            { code: 'E11', available: true },
            { code: 'E12', available: false },
        ],
    },
    {
        type: 'F',
        seat: [
            { code: 'F1', available: true },
            { code: 'F2', available: true },
            { code: 'F3', available: false },
            { code: 'F4', available: false },
            { code: 'F5', available: false },
            { code: 'F6', available: true },
            { code: 'F7', available: false },
            { code: 'F8', available: false },
            { code: 'F9', available: false },
            { code: 'F10', available: true },
            { code: 'F11', available: true },
            { code: 'F12', available: false },
        ],
    },
];

export const flightSeatReturn = [
    {
        type: 'A',
        seat: [
            { code: 'A1', available: true },
            { code: 'A2', available: false },
            { code: 'A3', available: true },
            { code: 'A4', available: true },
            { code: 'A5', available: true },
            { code: 'A6', available: false },
            { code: 'A7', available: false },
            { code: 'A8', available: true },
            { code: 'A9', available: true },
            { code: 'A10', available: true },
            { code: 'A11', available: false },
            { code: 'A12', available: true },
        ],
    },
    {
        type: 'B',
        seat: [
            { code: 'B1', available: true },
            { code: 'B2', available: false },
            { code: 'B3', available: true },
            { code: 'B4', available: true },
            { code: 'B5', available: true },
            { code: 'B6', available: false },
            { code: 'B7', available: false },
            { code: 'B8', available: true },
            { code: 'B9', available: true },
            { code: 'B10', available: true },
            { code: 'B11', available: false },
            { code: 'B12', available: true },
        ],
    },
    {
        type: 'C',
        seat: [
            { code: 'C1', available: true },
            { code: 'C2', available: false },
            { code: 'C3', available: true },
            { code: 'C4', available: false },
            { code: 'C5', available: true },
            { code: 'C6', available: false },
            { code: 'C7', available: false },
            { code: 'C8', available: true },
            { code: 'C9', available: true },
            { code: 'C10', available: true },
            { code: 'C11', available: false },
            { code: 'C12', available: true },
        ],
    },
    {
        type: 'D',
        seat: [
            { code: 'D1', available: true },
            { code: 'D2', available: true },
            { code: 'D3', available: true },
            { code: 'D4', available: false },
            { code: 'D5', available: false },
            { code: 'D6', available: false },
            { code: 'D7', available: false },
            { code: 'D8', available: false },
            { code: 'D9', available: false },
            { code: 'D10', available: true },
            { code: 'D11', available: true },
            { code: 'D12', available: false },
        ],
    },
    {
        type: 'E',
        seat: [
            { code: 'E1', available: true },
            { code: 'E2', available: true },
            { code: 'E3', available: true },
            { code: 'E4', available: false },
            { code: 'E5', available: false },
            { code: 'E6', available: false },
            { code: 'E7', available: false },
            { code: 'E8', available: false },
            { code: 'E9', available: false },
            { code: 'E10', available: true },
            { code: 'E11', available: true },
            { code: 'E12', available: false },
        ],
    },
    {
        type: 'F',
        seat: [
            { code: 'F1', available: true },
            { code: 'F2', available: true },
            { code: 'F3', available: false },
            { code: 'F4', available: false },
            { code: 'F5', available: false },
            { code: 'F6', available: true },
            { code: 'F7', available: false },
            { code: 'F8', available: false },
            { code: 'F9', available: false },
            { code: 'F10', available: true },
            { code: 'F11', available: true },
            { code: 'F12', available: false },
        ],
    },
];
